### ISSUE TITLE
Just wanted a couple of pointers on usage

### ISSUE THREAD

**Issue by nakulbende** [fogleman/demsphere#1]
Hey Michael, 

I have never used go - but was trying to make sense of your code. If you remember, I wanted to see if I can generate the texture on the inside of sphere, rather than outside to create a nicer lamp like shell. 

in main.go
```
triangulator := demsphere.NewTriangulator(
		im, 9, 12, 3396190, -8201, 21241, 50, 10, 1.0/3396190)
```
im = image file,  What are other things doing? details radius and output radius - and there is a min/ max for all of those. How do i use these variables to change size of sphere and elevation exaggeration? 

What I am trying to do - can it be done by basically giving a negative sign to normals - I see two places for this, which one of them is the right one?

In triangles.go: 
```
func (t *Triangle) Normal() Vector {
	ab := t.B.Sub(t.A)
	ac := t.C.Sub(t.A)
	return ab.Cross(ac).Normalize()
}
```
What would be the change?

Or perhaps in stl.go, i can change to
```
		d.N[0] = -float32(n.X)
		d.N[1] = -float32(n.Y)
		d.N[2] = -float32(n.Z)
```

Thanks in advance!

**Comment by fogleman** [comment]
I think you want to do something like this:

https://github.com/fogleman/demsphere/compare/shell

Here I create a second triangulator and run it on an inverted version of the image, scale it down a bit (that's the `*0.75` which you might want to tweak to control the skin thickness), then flip its normals.

**Comment by nakulbende** [comment]
Beautiful!!! I will give it a go - last request. Do you have the DEM images you used/ or where you got them for different planets?

**Comment by fogleman** [comment]
Just google e.g. "mars dem" which leads you to this excellent site:

https://astrogeology.usgs.gov/search/map/Mars/Topography/HRSC_MOLA_Blend/Mars_HRSC_MOLA_BlendDEM_Global_200mp

**Comment by nakulbende** [comment]
This is just fantastic Michael - than k you so much. I will share the results!
